App restart required: Redémarrage app requis
Application Starts with Main Window Hidden: Démarrage avec fenêtre principale cachée
Change: Modifier
Display navbar items only when the mouse hovers over the navigation bar to minimize visible UI elements: Afficher éléments navbar au survol souris pour minimiser les éléments UI visibles
Global System OS Hotkeys: Raccourcis globaux du système
Hide Collections Navbar: Masquer navbar collections
Hide collections menu dropdown on the navigation bar: Masquer menu déroulant collections dans navbar
Hide collections menu on the navbar: Masquer menu collections dans navbar
Hide the App Dock Icon: Masquer icône app du Dock
? Keep the main application window hidden when the app restarts. You can reopen it using the menu bar or taskbar menu, or using global hotkeys.
: Garder fenêtre principale cachée au redémarrage. Réouvrez via barre de menu, menu barre des tâches ou raccourcis globaux.
No keys set: Aucune touche définie
PasteBar Quick Paste: Collage rapide PasteBar
Press keys: Appuyez touches
Quick Paste Window: Fenêtre collage rapide
? Remove PasteBar app icon from the macOS Dock while keeping the app running in the background. The app remains accessible via the menu bar icon. Requires an app restart to take effect.
: Retirer icône PasteBar du Dock macOS. App reste en arrière-plan, accessible via icône barre de menus. Nécessite redémarrage.
Set: Définir
Set system OS hotkeys to show/hide the main app window and quick paste window: Définir raccourcis système pour afficher/masquer fenêtre principale et collage rapide
Show Navbar Items Hover: Afficher éléments navbar au survol
Show collections menu on the navbar: Afficher menu collections dans navbar
Show navbar elements on hover only: Afficher éléments navbar au survol uniquement
Show/Hide Main App Window: Afficher/Masquer fenêtre principale
Show/Hide Quick Paste Window: Afficher/Masquer fenêtre collage rapide